---
books:
    -   name: Wraith Squadron
        path: wraith_squadron
    -   name: Iron Fist
        path: iron_fist
    -   name: Solo Command
        path: solo_command
    -   name: Starfighters of Adumar
        path: starfighters_of_adumar
    -   name: 'Enemy Lines 1: Rebel Dream'
        path: rebel_dream
    -   name: 'Enemy Lines 2: Rebel Stand'
        path: rebel_stand
...

