---
author: Aaron Allston
books:
  wraith_squadron: Wraith Squadron
  iron_fist: Iron Fist
  solo_command: Solo Command
  starfighters_of_adumar: Starfighters of Adumar
  rebel_dream: 'Enemy Lines 1: Rebel Dream'
  rebel_stand: 'Enemy Lines 2: Rebel Stand'
