dist: trusty
env:
  global:
  - PATH=$HOME/.local/bin:$PATH
  - BUCKET=akerl-book-library
  - AWS_DEFAULT_REGION=us-east-1
  - secure: m1EHj9U4/uubCxct+RqD6PxTc2eiMaGzql+HyZcG3KGwPztsJuVtR3n8r3h0QgcTY7dcXMypu24SoGIvyt3vb4n9dvsJxdQjdej+5uMSOGaZ9BeIarUqUmyCqQeVZTSqWVL9KlCgAQBzHJfAxIhwSxoCW9Ax2pBKshfZCSwksTkn/9gbmqEquZHFfKTGYa0fmnnvLaZuAWc2fNcuF62+Kh4PhXaTS4+H6Jqv4nXsi0KZ9zK2vZx1Ml4jlSwxBOj0lBiAtpZky/PG/VAnSgsOopwKE9zt0o0ePfKJpgDMV0mnxAJKnR7NY+J2echaoXMLQTx7hu4DitiAjgd5VJ8VnpEDVgm/uzDJw/0Vo7YnoMeSh/xmEximKB7t2YEZnicyRoL4FbetJkBeQLj2gteC2hCRuIUApX8q5vDqBy2hb6KMDdGobym0Ls5c95N3+6/XOtjast8wxuzkaPXHZFaQbzNLqJ7EFfZDs/QEAgR+KyTc/y+YNjEwp2mrCVmn4chPdV0RkIkSDiODP0yM3ZkUVdJqnK0MIUaMMhHkf5RJaC8A3AcqwpmP3AsqZ1g2xzzxTzoOD7zPzI70du9dUjQzioQlaKhvB2a7Lp0+kHObjXnNXiw1vdcmH3PeiLX4Mekg7KnJwH5dH9s46UmQFosgzMgiCaXccB2gd53SqiJJODM=
  - secure: IH2Cp6NhgQmOJ/87ztjTjF3CgsmA33x7CrsEQDv5KhEOGp5H/mmmAqkilZ67WlzKBFYtUl+pf8HZCnVdfoNVrOV8nbeGFGC6SAxLsMjfjDavaZ10cnE5j9xO/mHBkOdInGXagxJrZrHdNQ0lb8LG4+3YmCJ/x2gEJcmVq+MEAr27exH0lSP7QapbwicEnWx3cSuwE5n/0XyXoh6q+49rS3G1QXIC3Xpvc8/EjFumFzs6waDLtwzsJw/bgiGuQdLkZWYIU/osUsNpcCC6Tl6yBJa61RqHn42+Cdwsdu3Kb1v5qcHYYR9zFe0MdaoqgoQwKOV7Cjgc63eESmJEeNDWfLrMnPwIU4+17/Sdop9azViQ+QTYlXAnD8YQ1MGxS0qhFZlMBrXE7KYe1iM8rn3toGGnITZhGvPfJGE17INq99WMsEsV8PebCwhcym8Hl4KbCiUzSaILJFGwrDgV5wR8/3hXYqr0AcVTQ7520OxXETbKPES/wkjitvfnsGIUwrR42MCXsICmfhmIkyFkgSgYcqyxs1RbE8YPVz3eisYYRskNPRvfFSOhjN7z2EHSBQbPAaIe0aXN1RJcq3kBJoQHu5QZiMUULkGWemDhj02z89nL1DsPWulsuc/zZegxTolZdznbIPDRhF7HNCFtk5RhHRzKFDihWZKv6lCB3bLujHQ=
install:
- go get github.com/akerl/madlibrarian
- pip install --user awscli
script: "./scripts/build.rb"
deploy:
  provider: script
  script: "./scripts/upload.rb || travis_terminate 1"
  skip_cleanup: true
  on:
    branch: master
notifications:
  email: false
  slack:
    rooms:
      secure: mkn0C1t3H5wRi1m7ZXTXH56cgtmErG3brmgX3NA9bbA1pwbX/cr/WxkXk7i008OR8vj0H7DWP8xaf76Fl4NyP2a5/OdAi1QyDDck+4wrfx9kXGkKChRTr1bvHMITvurKeD5uzvOL4KIqDS6LTUr2fMJEz+TlKuKP4YNybKym/3A9SzbZmj1TG8/g9sWk0IbeA+Oo4Im2AbgBXL2BJcOpn3lpQKvFLiVHGBUK7uAKDR7suUPyoDA5S9cSKXlpbmdb6Ybcypse5QQokSiOawxLNjZBa6H5qslhlSNvv8M6jNuMh1QwU1NK+GBrIhw7xMN+zqqTWWVyp4Gpq254H4farES4xa2Oc986NmQN+dlaZezCwXMGkSzRZl3WrWqD8W5lVYPA/kURMbmZSqwkMS7vQLynQ7rET2KYCBH9x5YUcnh0wlz6eJ/DacO1QaCEISrZSl7J1u9UWBNZUlFapjnZrFDAd+Qiha5uYvrZJ8f1WEh35WZgoSHG6zX7Cl3bwfZ78dH4UQVvJ0PIJtWuqzpHUJ5yJ0ArMxE1HnfYTOWVF3ulTCU6cokCOpFkA+iQQkwIQRAgl5qC4Cw9oLXTzXff/1hrwSd5kjW5kGcUu8dfkb6ikiCnNo/s2QNjhdFyaCF8Kda4wpBTJCOVZnhWJoEbMJ58ZqdgI9xMY7xwDYIwbd4=
