dist: trusty
env:
  global:
  - PATH=$HOME/.local/bin:$PATH
  - BUCKET=akerl-book-library
  - AWS_DEFAULT_REGION=us-east-1
  - secure: Pw+SJthOQe1RkolVrRg0BxfqrdaZVLAOSoeU6xrl5EgmFGgS+Z/zcwZfaP8q+uI4sCBJdeDYPhSu4yCjsH6Hav8RxQBO44wNxKfDWlOOpJ8120/fS4eJ2kblQb4YqJstiqekcYyh+m85ia0bTBXJTgyHZf7uY1n4btRMeJgFL7EYQff2OW3keG88wbksv3XQUBXPm7nBNwcLfhzE4we2edSa3m926cf1XUYllTX+XrzKUbbzSwy2wblIhhcKfsb7s/Eu3gFIJGrcpWa1iEKGgwFV6FkD73DklijvfbL5Ng0l9Y+Yfz/iNcXzIWLSFhnBdzIBDro6qhH+7JKozb7odysOMzTeAePRU6nmJANlnu4hP8QD4jVCBAaSLbog6ZTD6SU84wUM6RSp0Xw5NHxeyUZn8tvttNlrtoAuixw5CCpY+/qVQLeYqpz6sgpr1zejL5JjeXpjZLBtJfTG4X33eZCQePmdnEbtm8e4aX1PtILL0gnhuE4p1JW9CfUXiPfdjngJifndwSMkSxeimeAPr0CTn6UKEJojK/RjUP16l1eOmCOPz1b0ZDdDDh6vPCe+eH+bqrZ4KhUs3k1dw6h/dwoAUwkwsqy3A+mJvSOPF5DrUq8egSacaQDA4zJkfvI+1sUigMTeChHTLYrdaL1IUm0ZPf4xSfsYjOVtZsgD9j0=
  - secure: EOgFgiZSXP43eOXbd9WUWtLYgpGQCVEPn2MoeLXEdYS0ePcC9oxRuc1QEbbaKF3Q0D+yQ2s2wXE02evWgn+zxNpHol0MzwNjCUIK1mK9BT5KaW8Rw4zacKbYlevL90QDkLwyaIlTiw75hw+n6KxECFgRUn/CfZ+v68NfKvB7qWQfFCMzGBHqhWsh0bB9O5MjwaMiibJQ846NzT9CDXtdjzw7A5ljY34rTc1XhaaJWwXO9zlzbnbYKCutxyv/KyeNUAv+8F7RaSzEBdXJCUAnwXS+M5osRxeBv6bqTjrGKgfsr6ToufcoF1pheKROTK+AXpcbJ/6pn2cLcBVZJ0tx+2FipzGxe930gd/zwKmJ6JSlzjRtuUiSlXkTJaaRfE0YRT45k1J383e6At/jTorkDgXkeyDkfDKn/0sJiFngcZpLGREo6mVgC8IaFU8S3/JoSZFf/R2/ONeoo/NEbvvDUcIIRi//ULnhs5FcB1I/CaBZO/teN6tJCakOXzEz5cDcoLFl8DBpc4McHx2Nt0Us/Pmv2uXj5r1M5Jln6QSnAuoL1QIIrzIrCRUWUNu/9fuUVQifghVc1LG1yKgM4t6UzRbzlUyUHKi+YQKpnuHIeh1hotI2WWHp5Nx0pYJoyx21vD+T6jc/qCUKjFTnqvboL9yUjsq6mQLP6wwH3iyXjJ0=
install:
- go get github.com/akerl/madlibrarian
- pip install --user awscli
script: "./scripts/build.rb"
deploy:
  provider: script
  script: "./scripts/upload.rb"
  skip_cleanup: true
  on:
    branch: master
notifications:
  email: false
  slack:
    rooms:
      secure: mkn0C1t3H5wRi1m7ZXTXH56cgtmErG3brmgX3NA9bbA1pwbX/cr/WxkXk7i008OR8vj0H7DWP8xaf76Fl4NyP2a5/OdAi1QyDDck+4wrfx9kXGkKChRTr1bvHMITvurKeD5uzvOL4KIqDS6LTUr2fMJEz+TlKuKP4YNybKym/3A9SzbZmj1TG8/g9sWk0IbeA+Oo4Im2AbgBXL2BJcOpn3lpQKvFLiVHGBUK7uAKDR7suUPyoDA5S9cSKXlpbmdb6Ybcypse5QQokSiOawxLNjZBa6H5qslhlSNvv8M6jNuMh1QwU1NK+GBrIhw7xMN+zqqTWWVyp4Gpq254H4farES4xa2Oc986NmQN+dlaZezCwXMGkSzRZl3WrWqD8W5lVYPA/kURMbmZSqwkMS7vQLynQ7rET2KYCBH9x5YUcnh0wlz6eJ/DacO1QaCEISrZSl7J1u9UWBNZUlFapjnZrFDAd+Qiha5uYvrZJ8f1WEh35WZgoSHG6zX7Cl3bwfZ78dH4UQVvJ0PIJtWuqzpHUJ5yJ0ArMxE1HnfYTOWVF3ulTCU6cokCOpFkA+iQQkwIQRAgl5qC4Cw9oLXTzXff/1hrwSd5kjW5kGcUu8dfkb6ikiCnNo/s2QNjhdFyaCF8Kda4wpBTJCOVZnhWJoEbMJ58ZqdgI9xMY7xwDYIwbd4=
