---
author: JK Rowling
books:
  sorcerers_stone: The Sorcerer's Stone
  chamber_of_secrets: The Chamber of Secrets
  prisoner_of_azkaban: The Prisoner of Azkaban
  goblet_of_fire: The Goblet of Fire
  order_of_the_phoenix: The Order of the Phoenix
  halfblood_prince: The Half-Blood Prince
  deathly_hallows: The Deathly Hallows
