---
books:
    -   name: 'Force Heretic 1: Remnant'
        path: remnant
    -   name: 'Force Heretic 2: Refugee'
        path: refugee
    -   name: 'Force Heretic 3: Reunion'
        path: reunion
...
