---
author: Michael Stackpole
books:
  rogue_squadron: 'X-Wing: Rogue Squadron'
  wedges_gamble: Wedge's Gamble
  krytos_trap: The Krytos Trap
  bacta_war: The Bacta War
  isards_revenge: Isard's Revenge
  onslaught: 'Dark Tide 1: Onslaught'
  ruin: 'Dark Tide 2: Ruin'
