---
books:
    -   name: "Agents of Chaos 1: Hero's Trial"
        path: heros_trial
    -   name: "Agents of Chaos 2: Jedi Eclipse"
        path: jedi_eclipse
    -   name: The Unifying Force
        path: unifying_force
...
