---
books:
    -   name: 'Edge of Victory 1: Conquest'
        path: conquest
    -   name: 'Edge of Victory 2: Rebirth'
        path: rebirth
    -   name: The Final Prophecy
        path: final_prophecy
...
