---
author: Orson Scott Card
books:
  enders_game: Ender's Game
  speaker_for_the_dead: Speaker for the Dead
  xenocide: Xenocide
  children_of_the_mind: Children of the Mind
  enders_shadow: Ender's Shadow
  shadow_of_the_hegemon: Shadow of the Hegemon
  shadow_puppets: Shadow Puppets
  shadow_of_the_giant: Shadow of the Giant
  ender_in_exile: Ender in Exile
  first_meetings: First Meetings
