name: Build
on:
  pull_request:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.0'
    - name: Install madlibrarian
      run: go install github.com/akerl/madlibrarian@latest
    - name: Install config deps
      run: ./scripts/deps.sh
    - name: Build
      run: ./scripts/build.rb
    - name: Build config
      run: ./scripts/template.py config.yaml.j2 config.yaml
      env:
        SIGN_KEY: ${{ secrets.SIGN_KEY }}
        ENC_KEY: ${{ secrets.ENC_KEY }}
        DSLACK_TOKEN: ${{ secrets.DSLACK_TOKEN }}
        ASLACK_TOKEN: ${{ secrets.ASLACK_TOKEN }}
        HSLACK_TOKEN: ${{ secrets.HSLACK_TOKEN }}
    - name: Release
      if: github.ref == 'refs/heads/master'
      run: ./scripts/upload.rb
      env:
        BUCKET: akerl-book-library
        AWS_DEFAULT_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Release config
      if: github.ref == 'refs/heads/master'
      run: ./scripts/upload.sh config.yaml
      env:
        BUCKET: akerl-book-library
        AWS_DEFAULT_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Post to a Slack channel
      if: ${{ failure() }}
      uses: slackapi/slack-github-action@v1.18.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      with:
        payload: |
          {
            "text": "*${{ github.repository }}*\nBuild failed: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*${{ github.repository }}*\nBuild failed: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
              }
            ]
          }
